apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  namespace: expense
  # labels of deployment resource
  labels:
    app: nginx
    tier: nginx
    project: expense
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: nginx
      project: expense
      version: blue
  template:
    metadata:
      labels:
        app: nginx
        tier: nginx
        project: expense
        version: blue
    spec:
      containers:
      - name: nginx
        image: joindevops/nginx:{{ .Values.deployment.blueVersion }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: nginx