kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: expense
spec:
  selector: # labels are used as selectors
    app: nginx
    tier: nginx
    project: expense
    version: {{ .Values.service.currentVersion }}
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80