apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-green
  namespace: expense
  # labels of deployment resource
  labels:
    app: backend
    tier: backend
    project: expense
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
      version: green
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
        version: green
    spec:
      containers:
      - name: nginx
        image: joindevops/backend:v2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: backend